name: dart_application_test
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.1 <3.0.0'


dependencies:
  fast_base58: 
    path: ../../

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0
